version: "3.0"
services: 
    apps:
        build:
            context: .
            dockerfile: dockerfile
        container_name: app_flask
        ports: 
            - "80:8080"
        networks: 
            flask_net:
                ipv4_address: 7.7.7.2
    database:
        build:
            context: .
            dockerfile: myqlDockerfile
        container_name: mysql_flask
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: maulapor
            MYSQL_DATABASE: maulapor
        volumes:
            - ./db/:/var/lib/mysql
        networks:
            flask_net:
                ipv4_address: 7.7.7.3

networks: 
  flask_net:
    driver: bridge
    ipam:  
      config: 
        - subnet: "7.7.7.0/24"
