version: "3.0"
services: 
    database:
        
        ports: 
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        
    apps:
        ports: 
            - "5000:5000"
